# Generated by Django 5.0.7 on 2026-01-28 01:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="File name"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Upload date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("processing", "Processing"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="Upload status",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("validation", "Validation error"),
                            ("format", "Invalid file format"),
                            ("structure", "Invalid data structure"),
                            ("required_columns", "Missing required columns"),
                            ("empty_dates", "Empty values in Start/End columns"),
                            ("date_format", "Invalid date format"),
                            ("date_logic", "Start > End"),
                            ("numeric", "Error in numeric columns"),
                            ("other", "Other error"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="Error type",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error message"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="File size (bytes)"
                    ),
                ),
                (
                    "rows_processed",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Number of processed rows"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uploaded file",
                "verbose_name_plural": "Uploaded files",
                "db_table": "data_processing_data_file",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Year"
                    ),
                ),
                (
                    "advertiser",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Advertiser"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Brand"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "format_type",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Format"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Platform"
                    ),
                ),
                (
                    "impressions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Impressions",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created at"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="data_processing.datafile",
                        verbose_name="File",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data record",
                "verbose_name_plural": "Data records",
                "db_table": "data_processing_data_record",
                "ordering": ["file", "start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="datafile",
            index=models.Index(
                fields=["user", "-uploaded_at"], name="data_proces_user_id_6e5b78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datafile",
            index=models.Index(fields=["status"], name="data_proces_status_eacf44_idx"),
        ),
        migrations.AddIndex(
            model_name="datafile",
            index=models.Index(
                fields=["error_type"], name="data_proces_error_t_305579_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datarecord",
            index=models.Index(
                fields=["file", "year"], name="data_proces_file_id_ddca16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datarecord",
            index=models.Index(fields=["year"], name="data_proces_year_b4087b_idx"),
        ),
        migrations.AddIndex(
            model_name="datarecord",
            index=models.Index(
                fields=["start_date", "end_date"], name="data_proces_start_d_2f5d77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datarecord",
            index=models.Index(
                fields=["advertiser", "brand"], name="data_proces_adverti_c6d1ef_idx"
            ),
        ),
    ]
